# Generated by Django 3.2.6 on 2023-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='idd',
        ),
        migrations.AddField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
