# Generated by Django 3.2.6 on 2023-08-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230826_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='refresh_token',
        ),
    ]
