# Generated by Django 3.2.6 on 2023-08-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230826_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Ism',
        ),
    ]
