# Generated by Django 3.2.6 on 2023-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_test_ism'),
    ]

    operations = [
        migrations.AddField(
            model_name='ism',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
